version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/defaultbackend"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/heapster"
    schedule:
      interval: "daily"
